version: 0.0
Resources:
  - TransactionSimulatorAPI:
      Type: AWS::Lambda::Function
      Properties:
        Name: TransactionSimulatorAPI
        Alias: LIVE
        CurrentVersion: "$LATEST"
        TargetVersion: "$LATEST"
Hooks:
  - BeforeAllowTraffic: "arn:aws:lambda:us-east-1:864981715490:function:TransactionSimulatorAPI"
  - AfterAllowTraffic: "arn:aws:lambda:us-east-1:864981715490:function:TransactionSimulatorAPI"