version: 0.2

env:
  variables:
    TF_VERSION: "1.7.5"
    TF_PLAN_FILE: "tfplan"
    # Ensure any necessary environment variables for AWS credentials or backend configuration are set here
    # or passed from the CodePipeline.

phases:
  install:
    runtime-versions:
      # These were the lines that caused the error when commented out but the block was present.
      # They need to be uncommented or the whole `runtime-versions` block removed if not needed.
      nodejs: 20 # Explicitly set Node.js runtime if any Node.js tools are used in this buildspec
      python: 3.11 # Explicitly set Python runtime if any Python tools are used in this buildspec
    commands:
      - echo "Installing Terraform..."
      - mkdir -p /tmp/terraform_install
      - cd /tmp/terraform_install
      - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform_${TF_VERSION}_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - cd $CODEBUILD_SRC_DIR
      - echo "Verifying Terraform installation..."
      - terraform --version

  build:
    commands:
      - echo "Initializing Terraform..."
      - cd terraform
      - terraform init -backend-config="bucket=${TF_STATE_BUCKET_NAME}" -backend-config="key=${TF_STATE_KEY}" -backend-config="region=${AWS_REGION}" -reconfigure

      - echo "Running Terraform plan..."
      - terraform plan -out=${TF_PLAN_FILE}

  post_build:
    commands:
      - echo "Uploading Terraform plan artifact..."
      - mv ${TF_PLAN_FILE} $CODEBUILD_SRC_DIR/
      - echo "Terraform plan completed and artifact uploaded."

artifacts:
  files:
    - '${TF_PLAN_FILE}'
  discard-paths: yes
  name: TerraformPlanArtifact