version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js...
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - cd frontend
      - echo Checking Node.js version...
      - node -v
      - npm -v
      - echo Installing frontend dependencies...
      - npm install
      - cd ..
  build:
    commands:
      - echo Building frontend...
      - cd frontend
      - npm run build
      - echo Checking frontend/dist contents...
      - ls -la dist
      - ls -la dist/assets || echo "Assets directory not found!"
      - cd ..
  post_build:
    commands:
      - echo "Frontend build complete."
artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
cache:
  paths:
    - 'frontend/node_modules/**'