version: 0.2

env:
  variables:
    TF_VERSION: "1.7.5"
    TF_PLAN_FILE: "tfplan"

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "Installing Terraform..."
      - mkdir -p /tmp/terraform_install
      - cd /tmp/terraform_install
      - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform_${TF_VERSION}_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - cd $CODEBUILD_SRC_DIR
      - echo "Verifying Terraform installation..."
      - terraform --version

  pre_build:
    commands:
      - echo "=== ARTIFACT DIAGNOSTICS ==="
      - echo "CODEBUILD_SRC_DIR=$CODEBUILD_SRC_DIR"
      - echo "Checking for artifact-specific environment variables:"
      - env | grep CODEBUILD_SRC_DIR
      - echo "Contents of main source directory:"
      - ls -la $CODEBUILD_SRC_DIR
      - echo "Checking artifact directory:"
      - |
        if [ ! -z "$CODEBUILD_SRC_DIR_LambdaS3LocationArtifact" ]; then
          echo "LambdaS3LocationArtifact directory: $CODEBUILD_SRC_DIR_LambdaS3LocationArtifact";
          ls -la $CODEBUILD_SRC_DIR_LambdaS3LocationArtifact;
        else
          echo "CODEBUILD_SRC_DIR_LambdaS3LocationArtifact not set";
        fi

  build:
    commands:
      - echo "Loading Lambda S3 location from previous stage..."
      - echo "Using artifact directory $CODEBUILD_SRC_DIR_LambdaS3LocationArtifact"
      - source $CODEBUILD_SRC_DIR_LambdaS3LocationArtifact/build.env
      - echo "LAMBDA_S3_BUCKET=$LAMBDA_S3_BUCKET"
      - echo "LAMBDA_S3_KEY=$LAMBDA_S3_KEY"
      - echo "Initializing Terraform..."
      - cd terraform
      - terraform init -reconfigure
      - echo "Running Terraform plan..."
      - terraform plan -var="lambda_s3_bucket=${LAMBDA_S3_BUCKET}" -var="lambda_s3_key=${LAMBDA_S3_KEY}" -out=${TF_PLAN_FILE}

  post_build:
    commands:
      - echo "Uploading Terraform plan artifact..."
      - mv ${TF_PLAN_FILE} $CODEBUILD_SRC_DIR/
      - echo "Terraform plan completed and artifact uploaded."

artifacts:
  files:
    - 'tfplan'
  discard-paths: yes
  name: TerraformPlanArtifact