# buildspec-static-analysis.yml
# This buildspec runs static analysis tools on both Infrastructure as Code (Terraform)
# and application code (Lambda and Frontend).
version: 0.2

env:
  variables:
    CHECK_FAIL_ON: "NONE" # Set to "NONE" or "FAILURE"

phases:
  install:
    commands:
      - echo "Installing Python3 and pip for Checkov..."
      - sudo apt-get update -y
      - sudo apt-get install -y python3 python3-pip
      - echo "Installing Checkov (IaC security scanner)..."
      - pip3 install checkov

      - echo "Installing Node.js 20 for ESLint..."
      - curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - echo "Installing ESLint globally..."
      - sudo npm install -g eslint

      # Install ESLint specific dependencies for your backend (TypeScript)
      # These commands need to be very precise or they can cause YAML parsing issues.
      # `npm install --prefix .` is often for local module installation.
      # If these dependencies are meant to be project-level, 'npm install' without --prefix
      # in the respective directories is standard.
      - echo "Installing backend ESLint dependencies..."
      - | # Use multi-line literal style for complex commands if needed
        cd backend/
        npm install @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint-config-airbnb-base || true
        cd ..
      - echo "Installing frontend ESLint dependencies..."
      - | # Use multi-line literal style for complex commands if needed
        cd frontend/
        npm install eslint-plugin-react eslint-plugin-react-hooks @typescript-eslint/eslint-plugin @typescript-eslint/parser || true
        cd ..

  build:
    commands:
      - echo "Running Checkov for IaC security scanning on Terraform files..."
      - checkov -d terraform/ --framework terraform --output cli -o json > checkov_results.json || true
      - if [ "$CHECK_FAIL_ON" == "FAILURE" ] && grep -q '"failures": [^0]' checkov_results.json; then echo "Checkov found failures. Review checkov_results.json."; exit 1; fi

      - echo "Running ESLint for backend code (TypeScript)..."
      - eslint backend/src/ || true

      - echo "Running ESLint for frontend code (TypeScript/React)..."
      - eslint frontend/src/ || true

  post_build:
    commands:
      - echo "Static analysis complete. Review logs for findings."
artifacts:
  files:
    - 'checkov_results.json'