version: 0.2

phases:
  build:
    commands:
      - "echo 'Current directory:'"
      - "pwd"
      - "echo 'Files in current directory:'"
      - "ls -la"
      - "echo 'Looking for buildspec files:'"
      - "find . -name '*buildspec*' -type f"
      - "echo 'Contents of root directory:'"
      - "ls -la /"
      - "echo 'Contents of codebuild directory:'"
      - "ls -la /codebuild/output/src*/"