version: 0.2

env:
  variables:
    TF_VAR_supabase_url: ""
    TF_VAR_supabase_key: ""

phases:
  install:
    commands:
      - "echo Installing Terraform 1.5.7..."
      - "wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip"
      - "sudo unzip terraform_1.5.7_linux_amd64.zip -d /usr/local/bin/"
      - "rm terraform_1.5.7_linux_amd64.zip"
      - "echo Navigating to Terraform directory: ./terraform/"
      - "cd terraform/"
      - "echo Initializing Terraform backend..."
      - "terraform init -backend-config=\"bucket=transaction-simulator-terraform-tfstate\" -backend-config=\"key=transaction-simulator/terraform.tfstate\" -backend-config=\"region=us-east-1\""

  build:
    commands:
      - "echo Applying Terraform plan: plan.tfplan..."
      - "terraform apply \"plan.tfplan\""

  post_build:
    commands:
      - "echo Terraform apply completed successfully."
      - "terraform output -json > terraform_outputs.json"

artifacts:
  files:
    - "terraform_outputs.json"
  base-directory: "terraform/"