version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies for Lambda function..."
      - cd lambda
      - npm install
      - echo "Dependencies installed."

  build:
    commands:
      - echo "Zipping Lambda function code..."
      - zip -r ../lambda.zip .
      - echo "Lambda code zipped."
      - export LAMBDA_CODE_S3_BUCKET="transaction-simulator-lambda-code-${AWS_ACCOUNT_ID}-${AWS_DEFAULT_REGION}"
      - echo "Lambda S3 Bucket $LAMBDA_CODE_S3_BUCKET"
      - export LAMBDA_S3_KEY="lambda-packages/lambda-${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip"
      - echo "Lambda S3 Key $LAMBDA_S3_KEY"
      - echo "Uploading lambda.zip to S3..."
      - aws s3 cp ../lambda.zip "s3://${LAMBDA_CODE_S3_BUCKET}/${LAMBDA_S3_KEY}" --metadata-directive REPLACE --acl bucket-owner-full-control --sse AES256
      - echo "Lambda.zip uploaded to S3."
      - echo "LAMBDA_S3_BUCKET=$LAMBDA_CODE_S3_BUCKET" > build.env
      - echo "LAMBDA_S3_KEY=$LAMBDA_S3_KEY" >> build.env
      - echo "build.env file created with S3 location details."

  post_build:
    commands:
      - echo "Lambda packaging and upload completed."
      - ls -la build.env

artifacts:
  files:
    - lambda.zip
  discard-paths: yes
  name: LambdaArtifact

  secondary-artifacts:
    LambdaS3LocationArtifact:
      files:
        - build.env
      discard-paths: yes