version: 0.2

phases:
  install:
    commands:
      - "echo Installing Terraform 1.5.7..."
      - "wget -q https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip"
      - "sudo unzip -q terraform_1.5.7_linux_amd64.zip -d /usr/local/bin/"
      - "rm terraform_1.5.7_linux_amd64.zip"

  pre_build:
    commands:
      - "echo Navigating to Terraform directory..."
      - "cd terraform"
      - "echo Initializing Terraform backend..."
      - "terraform init -backend-config=\"bucket=transaction-simulator-terraform-tfstate\" -backend-config=\"key=transaction-simulator/terraform.tfstate\" -backend-config=\"region=us-east-1\""

  build:
    commands:
      - "echo Applying Terraform plan..."
      - "terraform apply -auto-approve plan.tfplan"
      - "echo Generating Terraform outputs..."
      - "terraform output -json > terraform_outputs.json"
      - "echo Terraform outputs generated:"
      - "cat terraform_outputs.json"

  post_build:
    commands:
      - "echo Terraform apply completed successfully."

artifacts:
  files:
    - "terraform_outputs.json"
  base-directory: "terraform"