version: 0.2

env:
  variables:
    TF_VAR_supabase_url: ""
    TF_VAR_supabase_key: ""

phases:
  install:
    commands:
      - echo Installing Terraform 1.5.7...
      - wget -q https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - sudo unzip -q terraform_1.5.7_linux_amd64.zip -d /usr/local/bin/
      - rm terraform_1.5.7_linux_amd64.zip
  pre_build:
    commands:
      - echo Navigating to Terraform directory...
      - cd terraform
      - echo Initializing Terraform backend...
      - terraform init -backend-config="bucket=transaction-simulator-terraform-tfstate" -backend-config="key=transaction-simulator/terraform.tfstate" -backend-config="region=us-east-1"
      - echo Verifying required files exist...
      - ls -la plan.tfplan # Keep this, as plan.tfplan IS in the input artifact (TerraformPlanArtifact)
      - echo "Frontend dist directory check (if needed for deployment)"
      - ls -la dist || true # Check if dist exists, but don't fail if not, as terraform applies it

  build:
    commands:
      - echo Applying Terraform plan...
      - terraform apply -auto-approve plan.tfplan
      # After apply, generate outputs for the next stage (Smoke Tests)
      - echo Generating Terraform outputs...
      - terraform output -json > terraform_outputs.json
      - mv terraform_outputs.json ../ # Move to root for artifacting

  post_build:
    commands:
      - echo Terraform apply completed successfully.
      - echo Verifying generated outputs...
      - ls -la terraform_outputs.json

artifacts:
  files:
    - terraform_outputs.json # This is the main output for the next stage
  base-directory: . # Terraform outputs are at the root