version: 0.2
phases:
  install:
    commands:
      - echo Installing Node.js...
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - cd frontend
      - npm install
  build:
    commands:
      - echo Building frontend...
      - npm run build
      - echo Checking frontend/dist contents...
      - ls -la dist
      - ls -la dist/assets
  artifacts:
    files:
      - '**/*'
    base-directory: 'frontend/dist'