version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd lambda
      - npm install
  build:
    commands:
      - echo Packaging Lambda function...
      - zip -r ../lambda.zip .
      - echo Creating appspec.yml for CodeDeploy...
      - |
        cat <<EOF > ../appspec.yml
        version: 0.0
        Resources:
          - TransactionSimulatorAPI:
              Type: AWS::Lambda::Function
              Properties:
                Name: TransactionSimulatorAPI
                Alias: LIVE
                CurrentVersion: "$LATEST"
                TargetVersion: "$LATEST"
        Hooks:
          - BeforeAllowTraffic: "arn:aws:lambda:us-east-1:864981715490:function:TransactionSimulatorAPI"
          - AfterAllowTraffic: "arn:aws:lambda:us-east-1:864981715490:function:TransactionSimulatorAPI"
        EOF
artifacts:
  files:
    - lambda.zip
    - appspec.yml
  base-directory: "."