version: 0.2

env:
  variables:
    TF_VERSION: "1.7.5"

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "Installing Terraform..."
      - mkdir -p /tmp/terraform_install
      - cd /tmp/terraform_install
      - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform_${TF_VERSION}_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - cd $CODEBUILD_SRC_DIR
      - terraform version

      - echo "Loading Lambda S3 location from previous stage..."
      # CRITICAL CHANGE: Use LambdaS3LocationArtifact as the directory name
      - . LambdaS3LocationArtifact/build.env
      - echo "LAMBDA_S3_BUCKET=$LAMBDA_S3_BUCKET"
      - echo "LAMBDA_S3_KEY=$LAMBDA_S3_KEY"

  build:
    commands:
      - echo "Initializing Terraform..."
      - cd terraform
      - terraform init -input=false -reconfigure

      - echo "Applying Terraform plan..."
      - terraform apply -auto-approve ../TerraformPlanArtifact/tfplan -input=false

  post_build:
    commands:
      - echo "Generating Terraform outputs..."
      - terraform output -json > ../terraform_outputs.json
      - echo "Terraform apply completed."

artifacts:
  files:
    - 'terraform_outputs.json'
  name: TerraformOutputsArtifact