version: 0.2
phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - export TF_VERSION="1.7.5"
      - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform_${TF_VERSION}_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform version
      - cd terraform
      - source ../LambdaS3LocationArtifact/build.env
      - echo "LAMBDA_S3_BUCKET=$LAMBDA_S3_BUCKET"
      - echo "LAMBDA_S3_KEY=$LAMBDA_S3_KEY"
      - terraform init -backend-config="bucket=$LAMBDA_S3_BUCKET" -backend-config="key=$LAMBDA_S3_KEY" -input=false

  build:
    commands:
      - terraform plan -out=tfplan.out -input=false

  post_build:
    commands:
      - echo "Terraform plan generated."
      - ls -la tfplan.out

artifacts:
  files:
    - terraform/tfplan.out
  discard-paths: yes